[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "lambda-python-remotion"
version = "0.0.1"
authors = [
  { name="Jonny Burger", email="jonny@remotion.dev" },
]
description = "Remotion Python Client"
readme = "README.md"
requires-python = ">=3.11"
classifiers = [
]

[project.urls]
"Homepage" = "https://remotion.dev/"
"Bug Tracker" = "https://github.com/remotion-dev/remotion/issues"