[build]
command = "mkdir packages/docs/build && touch packages/docs/build/index.html && cp packages/docs/_redirects packages/docs/build/_redirects"
publish = "packages/docs/build"

[build.environment]
NPM_FLAGS="--prefix=/dev/null"
NODE_VERSION = "14.15.3" 

[[plugins]]
package = "/.netlify/netlify-plugin-pnpm"

