version: 2.1

orbs:
  node: circleci/node@5.1.0
  win: circleci/windows@2.4.1

jobs:
  build-linux-x64:
    docker:
      - image: cimg/rust:1.66-node
    steps:
      - checkout
      - node/install:
          node-version: "16.13"
      - restore_cache:
          keys:
            - ffmpeg_source-linux-x64
      - run:
          command: node build.mjs
          working_directory: packages/renderer
      - store_artifacts:
          path: ffmpeg.tar.gz
      - save_cache:
          key: ffmpeg_source-linux-x64
          paths:
            - ffmpeg
  build-windows:
    executor:
      name: win/default
    steps:
      - checkout
      - restore_cache:
          keys:
            - ffmpeg_source-windows
      - run: choco install rust
      - run: choco install nodejs-lts
      - run: rustup toolchain install stable-x86_64-pc-windows-gnu
      - run: rustup default stable-x86_64-pc-windows-gnu
      - run:
          command: node build.mjs
          working_directory: packages/renderer
          environment:
            CARGO_NET_GIT_FETCH_WITH_CLI: "true"
      - store_artifacts:
          path: ffmpeg.tar.gz
      - save_cache:
          key: ffmpeg_source-windows
          paths:
            - ffmpeg

  build-linux-arm:
    machine:
      image: ubuntu-2004:202101-01
    resource_class: arm.medium
    steps:
      - checkout
      - node/install:
          node-version: "16.13"
      - restore_cache:
          keys:
            - ffmpeg_source-linux-arm
      - run: curl https://sh.rustup.rs -sSf | sh -s -- -y
      - run:
          command: node build.mjs
          working_directory: packages/renderer
      - store_artifacts:
          path: ffmpeg.tar.gz
      - save_cache:
          key: ffmpeg_source-linux-arm
          paths:
            - ffmpeg

  build-macos:
    macos:
      xcode: 13.4.1
    steps:
      - checkout
      - node/install:
          node-version: "16.13"
      - restore_cache:
          keys:
            - ffmpeg_source-macos
      - run: curl https://sh.rustup.rs -sSf | sh -s -- -y
      - run:
          command: node build.mjs
          working_directory: packages/renderer
      - store_artifacts:
          path: ffmpeg.tar.gz
      - save_cache:
          key: ffmpeg_source-macos
          paths:
            - ffmpeg

workflows:
  build_ffmpeg:
    jobs:
      - build-linux-x64
      - build-linux-arm
      - build-macos
      - build-windows
