# Putting this file into packages/ because VSCode Rust extension
# only searches 1 level for Cargofiles

[build]
# Calling the directory "target" and adding it to turbo.json
# TODO: Add libc field to JS
target-dir = "renderer/target"
