# Putting this file into packages/ because VSCode Rust extension
# only searches 1 level for Cargofiles

[build]
# Calling the directory "dist" so it gets cached by turborepo
# TODO: Change it to not conflict with JS
# TODO: Add libc field to JS
target-dir = "compositor/dist"
