# Putting this file into packages/ because VSCode Rust extension
# only searches 1 level for Cargofiles

[package]
name = "remotion-renderer"
version = "0.1.0"
authors = ["Jonny Burger <jonny@remotion.dev>"]
edition = "2021"

[dependencies]
png = "0.17.6"
serde = {version =  "1.0.151", features = ["derive"]}
serde_json = "1.0.89"
jpeg-decoder = "0.3"
jpeg-encoder = "0.5.1"
resvg = "0.28.0"
usvg = "0.28.0" 
tiny-skia = "0.8.2"
byteorder = "1.4.3"
tiff = "0.8.1"
threadpool = "1.8.1"
lazy_static = "1.4.0"
x264 = { git = "https://github.com/JonnyBurger/x264", rev = "f4789b4c9872e567e3dbf0e898d3a6cf485ecbef" }


[[bin]]
name = "compositor"
path = "renderer/rust/main.rs"

[profile.release]
#strip="debuginfo"
#lto = "fat"
#opt-level = 'z'
