# Putting this file into packages/ because VSCode Rust extension
# only searches 1 level for Cargofiles

[package]
name = "remotion-renderer"
version = "0.1.0"
authors = ["Jonny Burger <jonny@remotion.dev>"]
edition = "2021"

[dependencies]
png = "0.17.7"
serde = {version =  "1.0.151", features = ["derive"]}
serde_json = "1.0.89"
jpeg-decoder = "0.3"
jpeg-encoder = "0.5.1"
lazy_static = "1.4"
rayon = "1.7.0"
ffmpeg-next = {git = "https://github.com/remotion-dev/rust-ffmpeg", rev ="4fd44a7d048cd2b2f8c51ab8866bb30cbf9cca26"}

[[bin]]
name = "compositor"
path = "renderer/rust/main.rs"

