[package]
name = "image-transformer"
version = "0.1.0"
authors = ["Jonny Burger <jonny@remotion.dev>"]
edition = "2021"

[dependencies]
png = "0.17.7"
image = "0.24.5"
serde = {version =  "1.0.151", features = ["derive"]}
serde_json = "1.0.89"
jpeg-decoder = "0.3"



[[bin]]
name = "compositor"
path = "compositor/main.rs"
