on:
  push:
    branches:
      - main
  pull_request:
name: Install and Test
jobs:
  lambda-tests:
    runs-on: ubuntu-latest
    name: Lambda integration
    steps:
      - uses: actions/checkout@main
      - uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node_version }}
      - uses: Iamshankhadeep/setup-ffmpeg@v1.1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          version: ${{ matrix.versionffmpeg_version }}

      - name: Cache .pnpm-store
        uses: actions/cache@v1
        with:
          path: ~/.pnpm-store
          key: ${{ runner.os }}-node${{ matrix.node-version }}-${{ hashFiles('**/pnpm-lock.yaml') }}

      - name: Install pnpm
        run: curl -f https://get.pnpm.io/v6.16.js | node - add --global pnpm@6
        shell: bash

      - name: Install
        run: pnpm install --frozen-lockfile

      - name: Test
        run: |
          pnpm build
          pnpm run testlambda
  ssr-tests:
    runs-on: ubuntu-latest
    name: SSR integration
    steps:
      - uses: actions/checkout@main
      - uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node_version }}
      - uses: Iamshankhadeep/setup-ffmpeg@v1.1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          version: ${{ matrix.versionffmpeg_version }}

      - name: Cache .pnpm-store
        uses: actions/cache@v1
        with:
          path: ~/.pnpm-store
          key: ${{ runner.os }}-node${{ matrix.node-version }}-${{ hashFiles('**/pnpm-lock.yaml') }}

      - name: Install pnpm
        run: curl -f https://get.pnpm.io/v6.16.js | node - add --global pnpm@6
        shell: bash

      - name: Install
        run: pnpm install --frozen-lockfile

      - name: Test
        run: |
          pnpm build
          pnpm run testssr
  build:
    name: Build Node ${{ matrix.node_version }} - ffmpeg ${{ matrix.ffmpeg_version }} on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            node_version: 14
            ffmpeg_version: 4.4
          - os: windows-latest
            node_version: 14
            ffmpeg_version: 4.4
          - os: macos-latest
            node_version: 14
            ffmpeg_version: 4.4
          - os: ubuntu-latest
            node_version: 12
            ffmpeg_version: 4.4
          - os: ubuntu-latest
            node_version: 17
            ffmpeg_version: 4.4
          - os: ubuntu-latest
            node_version: 14
            ffmpeg_version: 5.0
          - os: ubuntu-latest
            node_version: 14
            ffmpeg_version: 4.1
    steps:
      - uses: actions/checkout@main
      - uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node_version }}
      - uses: Iamshankhadeep/setup-ffmpeg@v1.1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          version: ${{ matrix.ffmpeg_version }}

      - name: Cache .pnpm-store
        uses: actions/cache@v2
        with:
          path: ~/.pnpm-store
          key: deps-${{ runner.os }}-node${{ matrix.node_version }}

      - name: Install pnpm
        run: curl -f https://get.pnpm.io/v6.16.js | node - add --global pnpm@6
        shell: bash

      - name: Install
        run: pnpm install --frozen-lockfile

      - name: Cache node_modules/.cache
        uses: actions/cache@v2
        with:
          path: node_modules/.cache
          key: turbo-${{ runner.os }}-${{ matrix.ffmpeg_version }}-node${{ matrix.node_version }}
      - name: Cache dist/ folders
        uses: actions/cache@v2
        if: runner.os != 'windows'
        with:
          path: packages/**/dist
          key: dist-${{ runner.os }}-${{ matrix.ffmpeg_version }}-node${{ matrix.node_version }}

      - name: Build & Test
        if: runner.os != 'windows'
        run: |
          pnpm run ci
      - name: Build & Test (Windows)
        if: runner.os == 'windows'
        run: |
          pnpm run ci:windows
