on: push
name: Install and Test
jobs:
  build-ubuntu:
    name: Build
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          os: macos-latest
          os: ubuntu-latest
          os: windows-latest
    steps:
      - uses: actions/checkout@main
      - uses: actions/setup-node@main
      - uses: FedericoCarboni/setup-ffmpeg@v1
      - run: npm i
      - run: npx lerna bootstrap --ci
      - run: npm run build
      - run: npm test
