on: push
name: Install and Test
jobs:
  build-ubuntu:
    name: Build
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]
        ffmpeg:
          # Test with both FFMPEG 4.4 and FFMPEG 4.1
          ["FedericoCarboni/setup-ffmpeg@v1", "Iamshankhadeep/setup-ffmpeg@v1"]
    steps:
      - uses: actions/checkout@main
      - uses: actions/setup-node@main
      - uses: ${{ matrix.ffmpeg }}
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
      - run: npm i
      - run: npx lerna bootstrap --ci
      - run: npm run build
      # We need to call bootstrap again to link the CLI
      # binary to allow `npx remotion`
      - run: npx lerna bootstrap --ci
      - run: npm test
