on: push
name: Install and Test
jobs:
  build-ubuntu:
    name: Build
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]
    steps:
      - uses: actions/checkout@main
      - uses: actions/setup-node@main
      - uses: FedericoCarboni/setup-ffmpeg@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
      - run: npm i
      - run: npx lerna bootstrap --ci
      - run: npm run build
      - run: npx lerna bootstrap --ci
      - run: npm test
