on: push
name: Install and Test
jobs:
  build:
    name: Build
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@main
      - uses: actions/setup-node@main
      - run: npm i
      - name: Magic
        uses: JonnyBurger/10x-actions@master
        with:
          pod-dir: ios
          github-token: "${{ secrets.GITHUB_TOKEN }}"
      - run: npm test
