on: push
name: Install and Test
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@main
      - uses: actions/setup-node@main
      - run: npm i
      - run: npx lerna link
      - run: npx lerna bootstrap --ci
      - run: npm test
