on: push
name: Install and Test
jobs:
  build:
    name: Build Node ${{ matrix.node_version }} - ffmpeg ${{ matrix.ffmpeg_version }} on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]
        node_version: ['16']
        ffmpeg_version: ['4.1','4.4']
    steps:
      - uses: actions/checkout@main
      - uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node_version }}
      - uses: Iamshankhadeep/setup-ffmpeg@v1.1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          version: ${{ matrix.versionffmpeg_version }}
      - run: npm i
      - run: npx lerna bootstrap --ci
      - run: npm run build
      # We need to call bootstrap again to link the CLI
      # binary to allow `npx remotion`
      - run: npx lerna bootstrap --ci
      - run: npm test
